trigger:
- master

stages:
- stage: Build
  jobs:
    - job: Build

      pool:
        vmImage: 'windows-2019'

      steps:
      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 5.6.0'
        inputs:
          versionSpec: 5.6.0

      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          restoreSolution: 'demo-web/demo-web.sln'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet test'
        inputs:
          command: custom
          projects: 'demo-web/tests/demo-web-tests.csproj'
          custom: 'test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet publish'
        inputs:
          projects: 'demo-web/src/demo-web.csproj'
          arguments: '--configuration $(BuildConfiguration --output "$(Agent.TempDirectory)\WebAppContent\"'

      - task: ArchiveFiles@2
        displayName: 'archive files'
        inputs:
          rootFolderOrFile: '$(Agent.TempDirectory)\WebAppContent'
          includeRootFolder: false

      - task: PublishBuildArtifacts@1
        displayName: 'publish artifact: drop'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
        condition: succeededOrFailed()