trigger:
- master

stages:
- stage: Build
  jobs:
    - job: Build

      pool:
        vmImage: 'windows-2019'

      steps:
      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 5.6.0'
        inputs:
          versionSpec: 5.6.0

      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          restoreSolution: 'demo-web/demo-web.sln'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet test'
        inputs:
          command: test
          projects: 'demo-web/tests/demo-web-tests.csproj'
          arguments: '--logger "trx;LogFileName=testresults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'

      - script: |
          dotnet reportgenerator "-reports:$(Build.SourcesDirectory)/TestResults/Coverage/coverage.cobertura.xml" "-targetDir:$(Build.SourcesDirectory)/TestResults/Coverage/Reports" -tag:$(Build.BuildNumber) -reportTypes:htmlInline
        workingDirectory: $(Build.SourcesDirectory)/demo-web/tests
        displayName: 'dotnet reportgenerator'

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'
          failTaskOnFailedTests: true
        displayName: 'publish test results'

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'cobertura'
          summaryFileLocation: $(Build.SourcesDirectory)/TestResults/Coverage/**/coverage.cobertura.xml
          reportDirectory: $(Build.SourcesDirectory)/TestResults/Coverage/Reports
          failIfCoverageEmpty: false 
        displayName: 'publish code coverage results'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet publish'
        command: 'publish'
        inputs:
          projects: 'demo-web/src/demo-web.csproj'
          arguments: '--configuration $(BuildConfiguration) --output "$(Agent.TempDirectory)\WebAppContent\"'

      - task: ArchiveFiles@2
        displayName: 'archive files'
        inputs:
          rootFolderOrFile: '$(Agent.TempDirectory)\WebAppContent'
          includeRootFolder: false

      - task: PublishBuildArtifacts@1
        displayName: 'publish artifact: drop'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
        condition: succeeded()